name: Run Locket Bot 24/7
on:
  schedule:
    - cron: '0 */6 * * *' # Cứ 6 tiếng tự khởi động lại để tránh bị ngủ gật
  workflow_dispatch: # Cho phép bạn bấm nút chạy bằng tay

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot aiohttp motor pymongo

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
